### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by dgellow** [active-group/timbre-logstash#1]
Hello,

I'm interested by this project.
Could you add some documentation in your README ?

**Comment by mikesperber** [comment]
We'll merge this into the timbre mainline shortly, so watch there for the relevant doc bits.

**Comment by dgellow** [comment]
@mikesperber Ok, that's a good news :)

I spent some time reading your sources and timbre documentation, it was really easy to integrate your appender.
Just to share what I found, I have something like this in my timbre configuration.

``` clj
(timbre/merge-config!
 {:timestamp-opts {:pattern :iso8601}
  :appenders
  {:logstash
   (timbre-logstash/timbre-json-appender logstash-host logstash-port)}})
```

**Comment by dfrese** [comment]
I wrote something up, btw. Note that I'd say that :timestamp-opts is irrelevant for this appender as of version 0.3.0 (:instant is used directly, instead of :timestamp_).
